In [4]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.6-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\karthi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\karthi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.5-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\karthi\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp312-cp312-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.7 MB 2.8 MB/s eta 0:00:04
   ---- ----------------------------------- 1.0/9.7 MB 3.1 MB/s eta 0:00:03
   ------ --------------------------------- 1.6/9.7 MB 2.7 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/9.7 MB 2.7 MB/s eta 0:00:03
   ---------- ----------------------------- 2.6/9.7 MB 2.6 MB/s eta 0:00:03
   ------------- -------------------------- 3.1/9.7 MB 2.6 MB/s eta 0:00:03
   -------------- ------------------------- 3.4/9.7 MB 2.5 MB/s eta 0:00:03
   ---------------- ----------------------- 3.9/9.7 MB 2.6 MB/s eta 0:00:03
   ------------------ --------------------- 4.5/9.7 MB 2.4 MB/s eta 0:00:03
   -------------------- ------------------- 5.0/9.7 MB 2.5 MB/s eta 0:00:02
   ---------------------- ----------------- 5.5/9.7 MB 2.5 MB/s eta 0:00:02
   ------------------------ --------------- 6.0/9.7 MB 2.5 MB/s eta 0:00:02
   --------------------------- ------------ 6.6/9.7 MB 2.5 MB/s eta 0:00:02
   ----------------------------- ---------- 7.1/9.7 MB 2.5 MB/s eta 0:00:02
   ------------------------------ --------- 7.3/9.7 MB 2.4 MB/s eta 0:00:01
   ------------------------------- -------- 7.6/9.7 MB 2.3 MB/s eta 0:00:01
   --------------------------------- ------ 8.1/9.7 MB 2.3 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.7 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.7 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 2.4 MB/s eta 0:00:00
Downloading tzdata-2026.5-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, pandas
Successfully installed pandas-3.0.6 tzdata-2026.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: C:\Users\karthi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [96]:
import pandas as pd

In [ ]:
df=pd.read_csv("adult.data",header=None)
df
df.head(20)#first few rows
df.tail(10)#last few rows
df.sample(5)#random
df.shape#count and shows no.of rows and columns
df.columns = ["age","workclass","fnlwgt","education","educationNum","maritalStatus","occupation","relationship",
              "race",
              "gender",
              "capitalGain",
              "capitalLoss",
              "hoursPerWeek",
              "nativeCountry",
              "Above50K"]#for add columns
df
df.info()
df.isnull().sum()#to check the null values in the data if there in no null value that shows 0 if null values is there that shows a numbers
df=df.dropna()#for remove the null values rows (or) df.dropna(inplace=true)
df.duplicated().sum()#check for duplicates.
df.drop_duplicates(inplace=True)
df.info()
df.shape
df.describe()#stastical analyses a data
df['education'].unique()#to check the categories in cloumn

<class 'pandas.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            32561 non-null  int64
 1   workclass      32561 non-null  str
 2   fnlwgt         32561 non-null  int64
 3   education      32561 non-null  str
 4   educationNum   32561 non-null  int64
 5   maritalStatus  32561 non-null  str
 6   occupation     32561 non-null  str
 7   relationship   32561 non-null  str
 8   race           32561 non-null  str
 9   gender         32561 non-null  str
 10  capitalGain    32561 non-null  int64
 11  capitalLoss    32561 non-null  int64
 12  hoursPerWeek   32561 non-null  int64
 13  nativeCountry  32561 non-null  str
 14  Above50K       32561 non-null  str
dtypes: int64(6), str(9)
memory usage: 3.7 MB
<class 'pandas.DataFrame'>
Index: 32537 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            32537 non-null  int64
 1   workclass      32537 non-null  str
 2   fnlwgt         32537 non-null  int64
 3   education      32537 non-null  str
 4   educationNum   32537 non-null  int64
 5   maritalStatus  32537 non-null  str
 6   occupation     32537 non-null  str
 7   relationship   32537 non-null  str
 8   race           32537 non-null  str
 9   gender         32537 non-null  str
 10  capitalGain    32537 non-null  int64
 11  capitalLoss    32537 non-null  int64
 12  hoursPerWeek   32537 non-null  int64
 13  nativeCountry  32537 non-null  str
 14  Above50K       32537 non-null  str
dtypes: int64(6), str(9)
memory usage: 4.0 MB

<StringArray>
[   ' Bachelors',      ' HS-grad',         ' 11th',      ' Masters',
          ' 9th', ' Some-college',   ' Assoc-acdm',    ' Assoc-voc',
      ' 7th-8th',    ' Doctorate',  ' Prof-school',      ' 5th-6th',
         ' 10th',      ' 1st-4th',    ' Preschool',         ' 12th']
Length: 16, dtype: str

In [ ]:
print('one')
df.iloc[0:2,0:3]

one

   age          workclass  fnlwgt
0   39          State-gov   77516
1   50   Self-emp-not-inc   83311

In [35]:
df
df.iloc[0:5,0:5:3]

   age   education
0   39   Bachelors
1   50   Bachelors
2   38     HS-grad
3   53        11th
4   28   Bachelors

In [44]:
df.iloc[-1:-6:-1,3:6]

         education  educationNum        maritalStatus
32560      HS-grad             9   Married-civ-spouse
32559      HS-grad             9        Never-married
32558      HS-grad             9              Widowed
32557      HS-grad             9   Married-civ-spouse
32556   Assoc-acdm            12   Married-civ-spouse

In [46]:
df.iloc[1:10,5:10]

            maritalStatus          occupation    relationship    race   gender
1      Married-civ-spouse     Exec-managerial         Husband   White     Male
2                Divorced   Handlers-cleaners   Not-in-family   White     Male
3      Married-civ-spouse   Handlers-cleaners         Husband   Black     Male
4      Married-civ-spouse      Prof-specialty            Wife   Black   Female
5      Married-civ-spouse     Exec-managerial            Wife   White   Female
6   Married-spouse-absent       Other-service   Not-in-family   Black   Female
7      Married-civ-spouse     Exec-managerial         Husband   White     Male
8           Never-married      Prof-specialty   Not-in-family   White   Female
9      Married-civ-spouse     Exec-managerial         Husband   White     Male

In [51]:
df.iloc[0:10,[0,3,6]]

   age   education          occupation
0   39   Bachelors        Adm-clerical
1   50   Bachelors     Exec-managerial
2   38     HS-grad   Handlers-cleaners
3   53        11th   Handlers-cleaners
4   28   Bachelors      Prof-specialty
5   37     Masters     Exec-managerial
6   49         9th       Other-service
7   52     HS-grad     Exec-managerial
8   31     Masters      Prof-specialty
9   42   Bachelors     Exec-managerial

In [56]:
df.iloc[-1:-10:-1,3:5]

           education  educationNum
32560        HS-grad             9
32559        HS-grad             9
32558        HS-grad             9
32557        HS-grad             9
32556     Assoc-acdm            12
32555   Some-college            10
32554        Masters            14
32553        Masters            14
32552      Assoc-voc            11

In [58]:
df.iloc[0:20,[1,13]]

            workclass   nativeCountry
0           State-gov   United-States
1    Self-emp-not-inc   United-States
2             Private   United-States
3             Private   United-States
4             Private            Cuba
5             Private   United-States
6             Private         Jamaica
7    Self-emp-not-inc   United-States
8             Private   United-States
9             Private   United-States
10            Private   United-States
11          State-gov           India
12            Private   United-States
13            Private   United-States
14            Private               ?
15            Private          Mexico
16   Self-emp-not-inc   United-States
17            Private   United-States
18            Private   United-States
19   Self-emp-not-inc   United-States

In [59]:
df.iloc[-1:-5:-1,[0,5,6,7]]

       age        maritalStatus          occupation relationship
32560   52   Married-civ-spouse     Exec-managerial         Wife
32559   22        Never-married        Adm-clerical    Own-child
32558   58              Widowed        Adm-clerical    Unmarried
32557   40   Married-civ-spouse   Machine-op-inspct      Husband

In [61]:
df.iloc[1:10,[1,14]]

           workclass Above50K
1   Self-emp-not-inc    <=50K
2            Private    <=50K
3            Private    <=50K
4            Private    <=50K
5            Private    <=50K
6            Private    <=50K
7   Self-emp-not-inc     >50K
8            Private     >50K
9            Private     >50K

In [63]:
df.iloc[-10:-15:-1,[7,9,14]]

          relationship   gender Above50K
32551          Husband     Male    <=50K
32550          Husband     Male    <=50K
32549   Other-relative   Female    <=50K
32548    Not-in-family     Male    <=50K
32547          Husband     Male    <=50K

In [72]:
df.loc[0:5, ['age','education','maritalStatus']]

   age   education        maritalStatus
0   39   Bachelors        Never-married
1   50   Bachelors   Married-civ-spouse
2   38     HS-grad             Divorced
3   53        11th   Married-civ-spouse
4   28   Bachelors   Married-civ-spouse
5   37     Masters   Married-civ-spouse

In [73]:
df.loc[0:5,"age":"occupation":2]

   age  fnlwgt  educationNum          occupation
0   39   77516            13        Adm-clerical
1   50   83311            13     Exec-managerial
2   38  215646             9   Handlers-cleaners
3   53  234721             7   Handlers-cleaners
4   28  338409            13      Prof-specialty
5   37  284582            14     Exec-managerial

In [94]:
df.loc[(df.age >85)&(df.education==" Bachelors"),['age', 'education', 'educationNum', 'occupation']]

       age   education  educationNum        occupation
1935    90   Bachelors            13   Exec-managerial
4109    90   Bachelors            13                 ?
6232    90   Bachelors            13    Prof-specialty
8973    90   Bachelors            13             Sales
11996   90   Bachelors            13   Exec-managerial
15892   90   Bachelors            13   Exec-managerial
18277   90   Bachelors            13             Sales
18413   90   Bachelors            13    Prof-specialty
22220   90   Bachelors            13    Prof-specialty

In [95]:
df.loc[(df.age >85)|(df.education==" Bachelors"),['age', 'education', 'educationNum', 'occupation']]

       age   education  educationNum        occupation
0       39   Bachelors            13      Adm-clerical
1       50   Bachelors            13   Exec-managerial
4       28   Bachelors            13    Prof-specialty
9       42   Bachelors            13   Exec-managerial
11      30   Bachelors            13    Prof-specialty
...    ...         ...           ...               ...
32530   35   Bachelors            13                 ?
32531   30   Bachelors            13                 ?
32533   54   Bachelors            13   Exec-managerial
32536   34   Bachelors            13   Exec-managerial
32538   38   Bachelors            13    Prof-specialty

[5391 rows x 4 columns]

In [89]:
df['education'].unique()

<StringArray>
[   ' Bachelors',      ' HS-grad',         ' 11th',      ' Masters',
          ' 9th', ' Some-college',   ' Assoc-acdm',    ' Assoc-voc',
      ' 7th-8th',    ' Doctorate',  ' Prof-school',      ' 5th-6th',
         ' 10th',      ' 1st-4th',    ' Preschool',         ' 12th']
Length: 16, dtype: str

In [97]:
df.loc[(df.education==" Bachelors")|(df.gender==" Male"),['age','education']]

       age      education
0       39      Bachelors
1       50      Bachelors
2       38        HS-grad
3       53           11th
4       28      Bachelors
...    ...            ...
32553   32        Masters
32554   53        Masters
32555   22   Some-college
32557   40        HS-grad
32559   22        HS-grad

[23393 rows x 2 columns]

In [105]:
df.groupby('gender')['educationNum'].sum()

gender
Female    108020
Male      220012
Name: educationNum, dtype: int64

In [ ]:
df

,age,workclass,fnlwgt,education,educationNum,maritalStatus,occupation,relationship,race,gender,capitalGain,capitalLoss,hoursPerWeek,nativeCountry,Above50K
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
df['age']#for particular column

0        39
1        50
2        38
3        53
4        28
         ..
32556    27
32557    40
32558    58
32559    22
32560    52
Name: age, Length: 32537, dtype: int64