In [1]:
import pandas as pd

In [7]:
#Display the first 5 rows using iloc.
df.iloc[0:5]

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [12]:
#Display rows 10 to 20 and only the columns Glucose, BloodPressure, and BMI using iloc.
df.iloc[10:21,[7,5]]

    blood_glucose_level    bmi
10                   85  27.32
11                  100  54.70
12                  130  36.05
13                  200  25.69
14                  160  27.32
15                  126  27.32
16                  200  30.36
17                  158  24.48
18                   80  27.32
19                  159  25.72
20                   90  36.38

In [13]:
#Select the first 10 rows and first 5 columns using iloc.
df.iloc[0:10,0:5]

   gender   age  hypertension  heart_disease smoking_history
0  Female  80.0             0              1           never
1  Female  54.0             0              0         No Info
2    Male  28.0             0              0           never
3  Female  36.0             0              0         current
4    Male  76.0             1              1         current
5  Female  20.0             0              0           never
6  Female  44.0             0              0           never
7  Female  79.0             0              0         No Info
8    Male  42.0             0              0           never
9  Female  32.0             0              0           never

In [15]:
#Display the last 5 rows using iloc.
df.iloc[-1:-6:-1]

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
99999,Female,57.0,0,0,current,22.43,6.6,90,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0

In [17]:
#Select rows at index positions 0, 5, 10, and 15 using iloc.
df.iloc[0:16:5]

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
5,Female,20.0,0,0,never,27.32,6.6,85,0
10,Female,53.0,0,0,never,27.32,6.1,85,0
15,Male,78.0,0,0,No Info,27.32,6.6,126,0

In [18]:
#Select the Glucose column using iloc.
df.iloc[::,[7]]

       blood_glucose_level
0                      140
1                       80
2                      158
3                      155
4                      155
...                    ...
99995                   90
99996                  100
99997                  155
99998                  100
99999                   90

[100000 rows x 1 columns]

In [19]:
#Select the last 3 columns using iloc.
df.iloc[::,-1:-4:-1]

       diabetes  blood_glucose_level  HbA1c_level
0             0                  140          6.6
1             0                   80          6.6
2             0                  158          5.7
3             0                  155          5.0
4             0                  155          4.8
...         ...                  ...          ...
99995         0                   90          6.2
99996         0                  100          6.5
99997         0                  155          5.7
99998         0                  100          4.0
99999         0                   90          6.6

[100000 rows x 3 columns]

In [6]:
#Display the row with index 10 using loc.
df.loc[10]

gender                 Female
age                      53.0
hypertension                0
heart_disease               0
smoking_history         never
bmi                     27.32
HbA1c_level               6.1
blood_glucose_level        85
diabetes                    0
Name: 10, dtype: object

In [9]:
#Display rows with index 5 to 15 using loc.
df.loc[5:10]

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
5,Female,20.0,0,0,never,27.32,6.6,85,0
6,Female,44.0,0,0,never,19.31,6.5,200,1
7,Female,79.0,0,0,No Info,23.86,5.7,85,0
8,Male,42.0,0,0,never,33.64,4.8,145,0
9,Female,32.0,0,0,never,27.32,5.0,100,0
10,Female,53.0,0,0,never,27.32,6.1,85,0

In [13]:
#Select only Glucose and BMI columns for rows with index 10 to 20.
df.loc[10:20,['blood_glucose_level','bmi']]

    blood_glucose_level    bmi
10                   85  27.32
11                  100  54.70
12                  130  36.05
13                  200  25.69
14                  160  27.32
15                  126  27.32
16                  200  30.36
17                  158  24.48
18                   80  27.32
19                  159  25.72
20                   90  36.38

In [15]:
#Find all patients whose Glucose > 140 using loc.
df.loc[(df.blood_glucose_level>140)]

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
6,Female,44.0,0,0,never,19.31,6.5,200,1
8,Male,42.0,0,0,never,33.64,4.8,145,0
...,...,...,...,...,...,...,...,...,...
99989,Female,26.0,0,0,No Info,27.32,5.0,158,0
99992,Female,26.0,0,0,never,34.34,6.5,160,0
99993,Female,40.0,0,0,never,40.69,3.5,155,0
99994,Female,36.0,0,0,No Info,24.60,4.8,145,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0

In [17]:
#Find patients whose BMI > 30 and select only:
df.loc[(df.bmi>30),['blood_glucose_level','bmi']]

       blood_glucose_level    bmi
8                      145  33.64
11                     100  54.70
12                     130  36.05
16                     200  30.36
20                      90  36.38
...                    ...    ...
99979                  240  30.11
99982                  126  30.04
99992                  160  34.34
99993                  155  40.69
99998                  100  35.42

[23483 rows x 2 columns]

In [12]:
#Find patients whose BMI > 30 and select only:Glucose,BMI,diabetes Change the diapadies to 1 for patients whose Glucose > 200.
df.loc[(df['bmi'] > 30) & (df['blood_glucose_level'] > 200),'diabetes'] = 1
df.loc[(df['bmi'] > 30)&(df['blood_glucose_level'] > 200),['blood_glucose_level', 'bmi', 'diabetes']]

       blood_glucose_level    bmi  diabetes
87                     220  32.27         1
125                    280  31.70         1
146                    280  30.80         1
414                    260  40.31         1
518                    280  32.31         1
...                    ...    ...       ...
99763                  280  35.91         1
99867                  300  33.12         1
99938                  300  30.42         1
99957                  280  34.45         1
99979                  240  30.11         1

[1672 rows x 3 columns]

In [20]:
#Select patients whose Age > 50 and display Age, Glucose, and Outcome.
df.loc[(df.age>50),['age','blood_glucose_level']]

        age  blood_glucose_level
0      80.0                  140
1      54.0                   80
4      76.0                  155
7      79.0                   85
10     53.0                   85
...     ...                  ...
99984  80.0                   85
99986  63.0                  145
99995  80.0                   90
99997  66.0                  155
99999  57.0                   90

[38463 rows x 2 columns]

In [ ]:
#Find patients with:Glucose > 150 BMI > 30 and display their Glucose, BMI, and diabetes.
df.loc[(df.blood_glucose_level>150)&(df.bmi>30),['blood_glucose_level','bmi','diabetes']]

       blood_glucose_level    bmi  diabetes
16                     200  30.36         0
30                     200  31.75         0
39                     200  56.43         0
42                     159  32.02         0
55                     159  37.16         1
...                    ...    ...       ...
99957                  280  34.45         1
99962                  200  38.31         1
99979                  240  30.11         1
99992                  160  34.34         0
99993                  155  40.69         0

[10344 rows x 3 columns]

In [14]:
#Find the average Glucose level for each Outcome.
df.groupby('diabetes')['blood_glucose_level'].mean()

diabetes
0    132.852470
1    194.094706
Name: blood_glucose_level, dtype: float64

In [15]:
#Find the average BMI for each Outcome.
df.groupby('diabetes')['bmi'].mean()

diabetes
0    26.887163
1    31.988382
Name: bmi, dtype: float64

In [16]:
#Find the number of patients in each Outcome group.
df.groupby('diabetes')['diabetes'].count()

diabetes
0    91500
1     8500
Name: diabetes, dtype: int64

In [17]:
#Find the average Glucose for patients with Outcome = 1 and Outcome = 0 separately using groupby().
df.groupby('diabetes')['blood_glucose_level'].mean()

diabetes
0    132.852470
1    194.094706
Name: blood_glucose_level, dtype: float64

In [ ]:
#Find the top 5 patients with the highest Glucose using loc/iloc.
df.sort_values('blood_glucose_level',ascending=False).loc[:5]#loc
df.sort_values('blood_glucose_level',ascending=False).iloc[::].head(5)#iloc

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
99938,Male,55.0,0,1,former,30.42,6.2,300,1
41052,Female,66.0,1,0,never,35.30,6.2,300,1
96043,Male,43.0,1,0,former,35.39,9.0,300,1
95961,Female,45.0,0,0,current,50.05,6.0,300,1
95956,Male,72.0,0,0,former,27.32,7.5,300,1

In [18]:
#Create these age groups:< 30 → Young 30–50 → Middle > 50 → Senior Then find the average Glucose for each age group.
df['age_group']=pd.cut(df['age'],bins=[0,30,50,90],labels=['younger','old','senior'])
df.groupby('age_group')['blood_glucose_level'].mean()
df

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes,age_group
0,Female,80.0,0,1,never,25.19,6.6,140,0,senior
1,Female,54.0,0,0,No Info,27.32,6.6,80,0,senior
2,Male,28.0,0,0,never,27.32,5.7,158,0,younger
3,Female,36.0,0,0,current,23.45,5.0,155,0,old
4,Male,76.0,1,1,current,20.14,4.8,155,0,senior
...,...,...,...,...,...,...,...,...,...,...
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0,senior
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0,younger
99997,Male,66.0,0,0,former,27.83,5.7,155,0,senior
99998,Female,24.0,0,0,never,35.42,4.0,100,0,younger
99999,Female,57.0,0,0,current,22.43,6.6,90,0,senior

In [39]:
#Using groupby(), find the average BMI of diabetic patients (Outcome=1) by age group.
de=df[df['diabetes']==1]
de.groupby('age_group')['bmi'].mean()
de.groupby('age_group')['blood_glucose_level'].mean()

age_group
younger    192.109635
old        192.695287
senior     194.510526
Name: blood_glucose_level, dtype: float64

In [38]:
#Find which Outcome group has the highest average Glucose, BMI, and Age.
df.groupby('diabetes')[['blood_glucose_level','bmi','age']].mean()

          blood_glucose_level        bmi        age
diabetes
0                  132.852470  26.887163  40.115187
1                  194.094706  31.988382  60.946588

In [13]:
df=pd.read_csv("diabetes.csv")
df

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [ ]:
#create data set
df1=pd.DataFrame({'ID':[1,2,3,4],'NAME':['ram','raj','tom','dom'],'AGE':[21,23,20,21]})
df1

   ID NAME  AGE
0   1  ram   21
1   2  raj   23
2   3  tom   20
3   4  dom   21

In [51]:
df2=pd.DataFrame({'ID':[4,5,6,7],'salary':[50000,40000,28000,55000]})
df2

   ID  salary
0   4   50000
1   5   40000
2   6   28000
3   7   55000

In [ ]:
#merge data set
merged_df=pd.merge(df1,df2, on='ID',how='inner')
merged_df

   ID NAME  AGE  salary
0   4  dom   21   50000

In [53]:
#concat
concat_df=pd.concat([df1,df2])
concat_df

   ID NAME   AGE   salary
0   1  ram  21.0      NaN
1   2  raj  23.0      NaN
2   3  tom  20.0      NaN
3   4  dom  21.0      NaN
0   4  NaN   NaN  50000.0
1   5  NaN   NaN  40000.0
2   6  NaN   NaN  28000.0
3   7  NaN   NaN  55000.0

In [ ]:
#pivort_table   tablename|numerical column name|any column name|aggregation function.
p=pd.pivot_table(data=df1,values='ID',index='NAME',columns='AGE',aggfunc='count')
p

AGE    20   21   23
NAME
dom   NaN  1.0  NaN
raj   NaN  NaN  1.0
ram   NaN  1.0  NaN
tom   1.0  NaN  NaN

In [63]:
d=pd.DataFrame({"name":['ravi','raj','kumar','riya','suku','karthi','ram','jeni'],
   "age":[23,34,45,32,45,20,40,32],
   "course":['BGA','CS','CA','BGA','MATHS','SCIENCE','B-TECH','CS'],
   'rollno':[10,20,30,40,55,60,70,52]})
d

     name  age   course  rollno
0    ravi   23      BGA      10
1     raj   34       CS      20
2   kumar   45       CA      30
3    riya   32      BGA      40
4    suku   45    MATHS      55
5  karthi   20  SCIENCE      60
6     ram   40   B-TECH      70
7    jeni   32       CS      52

In [64]:
d=pd.pivot_table(data=d,values='rollno',index='course',columns='name',aggfunc='mean')
d

name     jeni  karthi  kumar   raj   ram  ravi  riya  suku
course
B-TECH    NaN     NaN    NaN   NaN  70.0   NaN   NaN   NaN
BGA       NaN     NaN    NaN   NaN   NaN  10.0  40.0   NaN
CA        NaN     NaN   30.0   NaN   NaN   NaN   NaN   NaN
CS       52.0     NaN    NaN  20.0   NaN   NaN   NaN   NaN
MATHS     NaN     NaN    NaN   NaN   NaN   NaN   NaN  55.0
SCIENCE   NaN    60.0    NaN   NaN   NaN   NaN   NaN   NaN